<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <base href="/">
    <title>Rescue</title>
    <meta name="author" content="Buildiful">
    <meta name="description" content="Modernizing emergency dispatch.">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/forestryio/ubuild-blocks@1.0.0/dist/css/ubuild.css"/>
  </head>
  <body>

<!-- Add your site or application content here -->
<p>---
title: Rescue
author: Buildiful
email: 
description: Modernizing emergency dispatch.
baseurl: "/"
url: https://rescue.care
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
timezone: Etc/UTC
</p>

  </body>
</html>